import { type VirtualKeyboardButtonInterface } from "@teleskop150750/t-virtual-keyboard/dist/src/types/types";

export const ru: Record<string, VirtualKeyboardButtonInterface[]> = {
  ru: [
    {
      code: "Backquote",
      label: "ё",
      value: "ё",
      capsLabel: "Ё",
      capsValue: "Ё",
      position: {
        row: 1,
        index: 1,
      },
      type: "default",
    },
    {
      code: "Digit1",
      label: "1",
      value: "1",
      capsLabel: "!",
      capsValue: "!",
      position: {
        row: 1,
        index: 2,
      },
      type: "default",
    },
    {
      code: "Digit2",
      label: "2",
      value: "2",
      capsLabel: '"',
      capsValue: '"',
      position: {
        row: 1,
        index: 3,
      },
      type: "default",
    },
    {
      code: "Digit3",
      label: "3",
      value: "3",
      capsLabel: "№",
      capsValue: "№",
      position: {
        row: 1,
        index: 4,
      },
      type: "default",
    },
    {
      code: "Digit4",
      label: "4",
      value: "4",
      capsLabel: ";",
      capsValue: ";",
      position: {
        row: 1,
        index: 5,
      },
      type: "default",
    },
    {
      code: "Digit5",
      label: "5",
      value: "5",
      capsLabel: "%",
      capsValue: "%",
      position: {
        row: 1,
        index: 6,
      },
      type: "default",
    },
    {
      code: "Digit6",
      label: "6",
      value: "6",
      capsLabel: ":",
      capsValue: ":",
      position: {
        row: 1,
        index: 7,
      },
      type: "default",
    },
    {
      code: "Digit7",
      label: "7",
      value: "7",
      capsLabel: "?",
      capsValue: "?",
      position: {
        row: 1,
        index: 8,
      },
      type: "default",
    },
    {
      code: "Digit8",
      label: "8",
      value: "8",
      capsLabel: "*",
      capsValue: "*",
      position: {
        row: 1,
        index: 9,
      },
      type: "default",
    },
    {
      code: "Digit9",
      label: "9",
      value: "9",
      capsLabel: "(",
      capsValue: "(",
      position: {
        row: 1,
        index: 10,
      },
      type: "default",
    },
    {
      code: "Digit0",
      label: "0",
      value: "0",
      capsLabel: ")",
      capsValue: ")",
      position: {
        row: 1,
        index: 11,
      },
      type: "default",
    },
    {
      code: "Minus",
      label: "-",
      value: "-",
      capsLabel: "_",
      capsValue: "_",
      position: {
        row: 1,
        index: 12,
      },
      type: "default",
    },
    {
      code: "Equal",
      label: "=",
      value: "=",
      capsLabel: "+",
      capsValue: "+",
      position: {
        row: 1,
        index: 13,
      },
      type: "default",
    },
    {
      code: "Backspace",
      label: "backspace",
      position: {
        row: 1,
        index: 14,
      },
      type: "backspace",
    },
    {
      label: "tab",
      code: "Tab",
      value: "\t",
      position: {
        row: 2,
        index: 1,
      },
      type: "default",
    },
    {
      code: "KeyQ",
      label: "й",
      value: "й",
      capsLabel: "Й",
      capsValue: "Й",
      position: {
        row: 2,
        index: 2,
      },
      type: "default",
    },
    {
      code: "KeyW",
      label: "ц",
      value: "ц",
      capsLabel: "Ц",
      capsValue: "Ц",
      position: {
        row: 2,
        index: 3,
      },
      type: "default",
    },
    {
      code: "KeyE",
      label: "у",
      value: "у",
      capsLabel: "У",
      capsValue: "У",
      position: {
        row: 2,
        index: 4,
      },
      type: "default",
    },
    {
      code: "KeyR",
      label: "к",
      value: "к",
      capsLabel: "К",
      capsValue: "К",
      position: {
        row: 2,
        index: 5,
      },
      type: "default",
    },
    {
      code: "KeyT",
      label: "е",
      value: "е",
      capsLabel: "Е",
      capsValue: "Е",
      position: {
        row: 2,
        index: 6,
      },
      type: "default",
    },
    {
      code: "KeyY",
      label: "н",
      value: "н",
      capsLabel: "Н",
      capsValue: "Н",
      position: {
        row: 2,
        index: 7,
      },
      type: "default",
    },
    {
      code: "KeyU",
      label: "г",
      value: "г",
      capsLabel: "г",
      capsValue: "г",
      position: {
        row: 2,
        index: 8,
      },
      type: "default",
    },
    {
      code: "KeyI",
      label: "ш",
      value: "ш",
      capsLabel: "Ш",
      capsValue: "Ш",
      position: {
        row: 2,
        index: 9,
      },
      type: "default",
    },
    {
      code: "KeyO",
      label: "щ",
      value: "щ",
      capsLabel: "Щ",
      capsValue: "Щ",
      position: {
        row: 2,
        index: 10,
      },
      type: "default",
    },
    {
      code: "KeyP",
      label: "з",
      value: "з",
      capsLabel: "З",
      capsValue: "З",
      position: {
        row: 2,
        index: 11,
      },
      type: "default",
    },
    {
      code: "BracketLeft",
      label: "[",
      value: "[",
      capsLabel: "{",
      capsValue: "{",
      position: {
        row: 2,
        index: 12,
      },
      type: "default",
    },
    {
      code: "BracketRight",
      label: "]",
      value: "]",
      capsLabel: "}",
      capsValue: "}",
      position: {
        row: 2,
        index: 13,
      },
      type: "default",
    },
    {
      code: "Backslash",
      label: "\\",
      value: "\\",
      capsLabel: "/",
      capsValue: "/",
      position: {
        row: 2,
        index: 14,
      },
      type: "default",
    },
    {
      code: "CapsLock",
      label: "caps",
      position: {
        row: 3,
        index: 1,
      },
      type: "caps",
    },
    {
      code: "KeyA",
      label: "ф",
      value: "ф",
      capsLabel: "Ф",
      capsValue: "Ф",
      position: {
        row: 3,
        index: 3,
      },
      type: "default",
    },
    {
      code: "KeyS",
      label: "ы",
      value: "ы",
      capsLabel: "Ы",
      capsValue: "Ы",
      position: {
        row: 3,
        index: 4,
      },
      type: "default",
    },
    {
      code: "KeyD",
      label: "в",
      value: "в",
      capsLabel: "В",
      capsValue: "В",
      position: {
        row: 3,
        index: 5,
      },
      type: "default",
    },
    {
      code: "KeyF",
      label: "а",
      value: "а",
      capsLabel: "А",
      capsValue: "А",
      position: {
        row: 3,
        index: 6,
      },
      type: "default",
    },
    {
      code: "KeyG",
      label: "п",
      value: "п",
      capsLabel: "П",
      capsValue: "П",
      position: {
        row: 3,
        index: 7,
      },
      type: "default",
    },
    {
      code: "KeyH",
      label: "р",
      value: "р",
      capsLabel: "Р",
      capsValue: "Р",
      position: {
        row: 3,
        index: 8,
      },
      type: "default",
    },
    {
      code: "KeyJ",
      label: "о",
      value: "о",
      capsLabel: "О",
      capsValue: "О",
      position: {
        row: 3,
        index: 9,
      },
      type: "default",
    },
    {
      code: "KeyK",
      label: "л",
      value: "л",
      capsLabel: "Л",
      capsValue: "Л",
      position: {
        row: 3,
        index: 10,
      },
      type: "default",
    },
    {
      code: "KeyL",
      label: "д",
      value: "д",
      capsLabel: "Д",
      capsValue: "Д",
      position: {
        row: 3,
        index: 11,
      },
      type: "default",
    },
    {
      code: "Semicolon",
      label: "ж",
      value: "ж",
      capsLabel: "Ж",
      capsValue: "Ж",
      position: {
        row: 3,
        index: 12,
      },
      type: "default",
    },
    {
      code: "Quote",
      label: "э",
      value: "э",
      capsLabel: "Э",
      capsValue: "Э",
      position: {
        row: 3,
        index: 14,
      },
      type: "default",
    },
    {
      code: "Enter",
      label: "enter",
      value: "\n",
      position: {
        row: 3,
        index: 15,
      },
      type: "default",
    },
    {
      code: "ShiftLeft",
      label: "shift",
      position: {
        row: 4,
        index: 1,
      },
      type: "shift",
    },
    {
      code: "KeyZ",
      label: "я",
      value: "я",
      capsLabel: "Я",
      capsValue: "Я",
      position: {
        row: 4,
        index: 2,
      },
      type: "default",
    },
    {
      code: "KeyX",
      label: "ч",
      value: "ч",
      capsLabel: "Ч",
      capsValue: "Ч",
      position: {
        row: 4,
        index: 3,
      },
      type: "default",
    },
    {
      code: "KeyC",
      label: "с",
      value: "с",
      capsLabel: "С",
      capsValue: "С",
      position: {
        row: 4,
        index: 4,
      },
      type: "default",
    },
    {
      code: "KeyV",
      label: "м",
      value: "м",
      capsLabel: "М",
      capsValue: "М",
      position: {
        row: 4,
        index: 5,
      },
      type: "default",
    },
    {
      code: "KeyB",
      label: "и",
      value: "и",
      capsLabel: "И",
      capsValue: "И",
      position: {
        row: 4,
        index: 6,
      },
      type: "default",
    },
    {
      code: "KeyN",
      label: "т",
      value: "т",
      capsLabel: "Т",
      capsValue: "Т",
      position: {
        row: 4,
        index: 7,
      },
      type: "default",
    },
    {
      code: "KeyM",
      label: "ь",
      value: "ь",
      capsLabel: "Ь",
      capsValue: "Ь",
      position: {
        row: 4,
        index: 8,
      },
      type: "default",
    },
    {
      code: "Comma",
      label: "б",
      value: "б",
      capsLabel: "Б",
      capsValue: "Б",
      position: {
        row: 4,
        index: 9,
      },
      type: "default",
    },
    {
      code: "Period",
      label: "ю",
      value: "ю",
      capsLabel: "Ю",
      capsValue: "Ю",
      position: {
        row: 4,
        index: 10,
      },
      type: "default",
    },
    {
      code: "Slash",
      label: ".",
      value: ".",
      capsLabel: ",",
      capsValue: ",",
      position: {
        row: 4,
        index: 11,
      },
      type: "default",
    },
    {
      code: "ShiftRight",
      label: "shift",
      position: {
        row: 4,
        index: 12,
      },
      type: "shift",
    },
    {
      code: ".com",
      label: ".com",
      value: ".com",
      position: {
        row: 5,
        index: 1,
      },
      type: "default",
    },
    {
      code: "@",
      label: "@",
      value: "@",
      position: {
        row: 5,
        index: 2,
      },
      type: "default",
    },
    {
      code: "Space",
      label: " ",
      value: " ",
      position: {
        row: 5,
        index: 3,
      },
      type: "default",
    },
  ],
};
